# Name of the service being written
name: eshop

# Version of the service
version:
  major: 1
  minor: 0
  maintenance: 0

server:
  servlet:
    context-path: /api/

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/Development/Projects/workspace_intellij/eShop/db/testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: DEBUG

swagger:
  version: ${version.major}.${version.minor}.${version.maintenance}
  title: eShop REST API
  description: Spring Boot REST API eShop Platform. Version ${swagger.version}
  license:
    title: "eShop"
    url: "https://www.xyz.com"
  contact:
    name: "eShop"
    url: "https://xyz.com"
    email: "abc@def.com"
